// Generated by CoffeeScript 1.6.3
var Earth, MapCtrl, aussieState, calculateTimeout, failureCB, initCB, panToAustralia, panToState, pan_through_array, pan_through_schools, pan_through_states, run_slide_show, schoolsInStates, setUpEarth, statePanTime;

setUpEarth = function() {
  return google.earth.createInstance('map3d', initCB, failureCB);
};

initCB = function(instance) {
  window.ge = instance;
  return ge.getWindow().setVisibility(true);
};

failureCB = function(errorCode) {
  return console.log(errorCode);
};

google.setOnLoadCallback(setUpEarth);

run_slide_show = function(earth) {
  var timeout;
  pan_through_states(schoolsInStates);
  timeout = calculateTimeout(schoolsInStates);
  return setTimeout(run_slide_show, 1000 * 45);
};

MapCtrl = function($scope) {
  window.earth = new Earth($scope);
  run_slide_show(earth);
  return $scope.getClass = function(school) {
    if (school === $scope.selectedSchool) {
      return "logo-colour";
    } else {
      return "logo-grey";
    }
  };
};

Earth = (function() {
  function Earth(scope) {
    this.scope = scope;
  }

  Earth.prototype.setViewTo = function(location) {
    var lookAt;
    this.scope.title = location.name;
    this.scope.$apply();
    console.log("Hey we're at " + location.name);
    if (location.lat) {
      console.log(location.lat);
      lookAt = ge.getView().copyAsLookAt(ge.ALTITUDE_RELATIVE_TO_GROUND);
      lookAt.setRange(location.range || 564.00);
      lookAt.setLatitude(location.lat);
      lookAt.setLongitude(location.lng);
      ge.getView().setAbstractView(lookAt);
    }
    if (location.logo) {
      this.scope.selectedSchool = location;
      this.scope.$apply();
    }
    if (location.schools) {
      this.scope.schools = location.schools;
      this.scope.$apply();
    }
    if (location.name === "Australia") {
      this.scope.schools = [];
      return this.scope.$apply();
    }
  };

  return Earth;

})();

schoolsInStates = [
  {
    name: "Victoria",
    range: 1133048,
    lng: 144.53876250295943,
    lat: -37.96765428547502,
    schools: [
      {
        name: "Camberwell Grammar",
        logo: "camberwell",
        lat: -37.8169075,
        lng: 145.0682967
      }, {
        name: "Xavier College",
        logo: "xavier",
        lat: -37.812269,
        lng: 145.031685
      }, {
        name: "Glen Waverley Secondary College",
        logo: "gwsc",
        lat: -37.8780251,
        lng: 145.16218
      }, {
        name: "Fintona Girls' School",
        logo: "fintona",
        lat: -37.8151431,
        lng: 145.079504
      }
    ]
  }, {
    name: "Western Australia",
    range: 2000000,
    lat: -27.6728168,
    lng: 121.6283098,
    schools: [
      {
        name: "John XXIII College",
        logo: "johnxxii",
        lat: -32.006682,
        lng: 116.038843
      }, {
        name: "Perth College",
        logo: "perth",
        lat: -31.931425,
        lng: 115.875297
      }, {
        name: "Penrhos College",
        logo: "penrhos",
        lat: -31.9971921,
        lng: 115.8721388
      }, {
        name: "Aquinas College",
        logo: "aquinas",
        lat: -32.024612,
        lng: 115.865683
      }
    ]
  }, {
    name: "South Australia",
    range: 1800000,
    lat: -29.9270476726815,
    lng: 138.20333108807867,
    schools: [
      {
        name: "Concordia College",
        logo: "concordia",
        lat: -34.9595118,
        lng: 138.6173848
      }, {
        name: "Pulteney Gramar",
        logo: "pulteney",
        lat: -34.9352115,
        lng: 138.6024578
      }, {
        name: "St. George's College",
        logo: "stgeorge",
        lat: -34.9223551,
        lng: 138.570423
      }, {
        name: "Trinity College, Gawler",
        logo: "trinity",
        lat: -34.6386448,
        lng: 138.6464245
      }
    ]
  }, {
    name: "New South Wales",
    range: 1750000,
    lat: -27.72857752890055,
    lng: 147.16564159039075,
    schools: [
      {
        name: "Kambala",
        logo: "kambala",
        lat: -33.8647888,
        lng: 151.2715316,
        name: "SCEGGS Darlinghurst",
        logo: "sceggs",
        lat: -33.876144,
        lng: 151.218369,
        name: "St. Aloysius' College",
        logo: "aloysius",
        lat: -33.8484373,
        lng: 151.2143868,
        name: "Presbyterian Ladies College, Sydney",
        logo: "plc",
        lat: -33.881386,
        lng: 151.1154961
      }
    ]
  }, {
    name: "Queensland",
    range: 2457255,
    lat: -18.846606463003678,
    lng: 145.39413779269196,
    schools: [
      {
        name: "Rockhampton Grammar",
        logo: "rockhampton",
        lat: -23.3851158,
        lng: 150.4940152,
        name: "A.B. Paterson College",
        logo: "abpat",
        lat: -27.9270641,
        lng: 153.3601713,
        name: "Citipointe Christian College",
        logo: "citipointe",
        lat: -27.534798,
        lng: 153.113118,
        name: "St. John's Anglican College",
        logo: "stjohns",
        lat: -27.6125928,
        lng: 152.961073
      }
    ]
  }, {
    name: "Northern Territory",
    range: 2457255,
    lat: -20.09994393657499,
    lng: 134.62769228738617,
    schools: [
      {
        name: "St. Philip's College",
        logo: "stphilips",
        lat: -23.690934,
        lng: 133.882398,
        name: "Kormilda College",
        logo: "kormilda",
        lat: -12.4436,
        lng: 130.9229
      }
    ]
  }, {
    name: "Australian Capital Territory",
    range: 16722.5264822886,
    lat: -35.29642006461715,
    lng: 149.140001506044,
    schools: [
      {
        name: "Radford College",
        logo: "radford",
        lat: -35.2438889,
        lng: 149.0880556,
        name: "Marist College",
        logo: "marist",
        lat: -35.3597768,
        lng: 149.0884452
      }
    ]
  }, {
    name: "South East Asia",
    range: 4400000,
    lat: 11.801464426569357,
    lng: 102.61731840153027,
    schools: [
      {
        name: "International School of Kuala Lumpur",
        logo: "iskl",
        lat: 3.161711,
        lng: 101.7557627,
        name: "Jakarta International School",
        logo: "jis",
        lat: -6.28564,
        lng: 106.78803,
        name: "Bangkok Patana School",
        logo: "patana",
        lat: 13.6617875,
        lng: 100.6221838
      }
    ]
  }, {
    name: "China",
    range: 4400000,
    lat: 33.4148047064862,
    lng: 97.74769944153013,
    schools: [
      {
        name: "Nanjing International School",
        logo: "nanjing",
        lat: 32.0791939,
        lng: 118.7511441,
        name: "Tianjin International School",
        logo: "tianjin",
        lat: 39.0559337,
        lng: 117.2724261
      }
    ]
  }
];

pan_through_array = function(array, callback, timeout) {
  var iterator, length, timer, timerFunction;
  console.log("IMMA LOOP THROUGH DIS ARRAY " + array);
  iterator = 0;
  length = array.length;
  timerFunction = function() {
    callback(array[iterator]);
    if (iterator === length - 1) {
      clearInterval(timer);
    }
    iterator++;
  };
  return timer = setInterval(timerFunction, timeout);
};

pan_through_schools = function(schools) {
  var callback, timeout;
  timeout = 5000;
  callback = function(school) {
    window.earth.setViewTo(school);
  };
  return pan_through_array(schools, callback, timeout);
};

pan_through_states = function(states) {
  var callback, timeout;
  timeout = 20 * 1000;
  callback = function(state) {
    panToState(state);
    if (aussieState(state)) {
      return setTimeout(panToAustralia, statePanTime(state));
    }
  };
  return pan_through_array(states, callback, timeout);
};

panToAustralia = function() {
  var australia;
  australia = {
    name: "Australia",
    range: 4700000,
    lng: 135.307,
    lat: -26.91234
  };
  return window.earth.setViewTo(australia);
};

panToState = function(state) {
  window.earth.setViewTo(state);
  pan_through_schools(state.schools);
};

calculateTimeout = function(array) {
  var panTime, state, timeout, total, _i, _len;
  total = array.length;
  total = total * 2;
  total = total - 2;
  for (_i = 0, _len = array.length; _i < _len; _i++) {
    state = array[_i];
    total += state.schools.length;
  }
  panTime = 1000 * 5;
  return timeout = total * panTime;
};

statePanTime = function(state) {
  return (state.schools.length + 1) * 5000;
};

aussieState = function(state) {
  return state === !"China" || "South East Asia";
};
