// Generated by CoffeeScript 1.6.3
(function() {
  var Earth, failureCB, initCB, run_slide_show, setUpEarth;

  setUpEarth = function() {
    return google.earth.createInstance('map3d', initCB, failureCB);
  };

  initCB = function(instance) {
    window.google_earth = instance;
    return window.google_earth.getWindow().setVisibility(true);
  };

  failureCB = function(errorCode) {
    return console.log(errorCode);
  };

  Earth = (function() {
    function Earth() {}

    Earth.prototype.setViewTo = function(location) {
      if (location.name) {
        return console.log("Hey we're at " + location.name);
      } else {
        return console.log("Yo here's " + location);
      }
    };

    return Earth;

  })();

  google.setOnLoadCallback(setUpEarth);

  run_slide_show = function() {
    var $scope, earth, pan_through_schools, schools, schools_in_states, state;
    earth = new Earth;
    $scope = {};
    pan_through_schools = function(schools) {
      var doSetTimeout, school, time, _i, _len, _results;
      console.log("IMMA LOOP THROUGH DEM SCHOOLS " + schools);
      doSetTimeout = function(school, time) {
        return setTimeout(function(school) {
          return earth.setViewTo(school);
        }, time);
      };
      time = 5000;
      _results = [];
      for (_i = 0, _len = schools.length; _i < _len; _i++) {
        school = schools[_i];
        doSetTimeout(school, time);
        _results.push(time += 5000);
      }
      return _results;
    };
    schools_in_states = {
      "Victoria": [
        {
          name: "Camberwell Grammar",
          logo: "http://catholicschoolsguide.com.au/wp-content/uploads/xavier-college1.jpg"
        }, {
          name: "Xavier College",
          logo: "http://catholicschoolsguide.com.au/wp-content/uploads/xavier-college1.jpg"
        }
      ]
    };
    for (state in schools_in_states) {
      schools = schools_in_states[state];
      earth.setViewTo(state);
      $scope.title = state;
      $scope.highlighted = null;
      pan_through_schools(schools);
    }
    return setTimeout(run_slide_show, 1000 * 30);
  };

  run_slide_show();

}).call(this);
