// Generated by CoffeeScript 1.6.3
var Earth, failureCB, initCB, run_slide_show, setUpEarth;

setUpEarth = function() {
  return google.earth.createInstance('map3d', initCB, failureCB);
};

initCB = function(instance) {
  window.ge = instance;
  return ge.getWindow().setVisibility(true);
};

failureCB = function(errorCode) {
  return console.log(errorCode);
};

Earth = (function() {
  function Earth() {}

  Earth.prototype.setViewTo = function(location) {
    var lookAt;
    document.getElementById("school-title").innerHTML = location.name;
    console.log("Hey we're at " + location.name);
    if (location.lat) {
      console.log(location.lat);
      lookAt = ge.getView().copyAsLookAt(ge.ALTITUDE_RELATIVE_TO_GROUND);
      lookAt.setRange(location.range || 564.00);
      lookAt.setLatitude(location.lat);
      lookAt.setLongitude(location.lng);
      return ge.getView().setAbstractView(lookAt);
    }
  };

  return Earth;

})();

google.setOnLoadCallback(setUpEarth);

run_slide_show = function() {
  var $scope, earth, pan_through_array, pan_through_schools, pan_through_states, schools_in_states;
  earth = new Earth;
  $scope = {};
  pan_through_array = function(array, callback, timeout) {
    var iterator, length, timer, timerFunction;
    console.log("IMMA LOOP THROUGH DIS ARRAY " + array);
    iterator = 0;
    length = array.length;
    timerFunction = function() {
      callback(array[iterator]);
      if (iterator === length - 1) {
        clearInterval(timer);
      }
      iterator++;
    };
    return timer = setInterval(timerFunction, timeout);
  };
  pan_through_schools = function(schools) {
    var callback, timeout;
    timeout = 3000;
    callback = function(school) {
      earth.setViewTo(school);
    };
    return pan_through_array(schools, callback, timeout);
  };
  pan_through_states = function(states) {
    var callback, timeout;
    timeout = 10000;
    callback = function(state) {
      earth.setViewTo(state);
      $scope.title = state;
      $scope.highlighted = null;
      pan_through_schools(state.schools);
    };
    return pan_through_array(states, callback, timeout);
  };
  schools_in_states = [
    {
      name: "Victoria",
      range: 1133048,
      lng: 144.53876250295943,
      lat: -37.96765428547502,
      schools: [
        {
          name: "Camberwell Grammar",
          logo: "http://catholicschoolsguide.com.au/wp-content/uploads/xavier-college1.jpg",
          lat: -37.8169075,
          lng: 145.0682967
        }, {
          name: "Xavier College",
          logo: "http://catholicschoolsguide.com.au/wp-content/uploads/xavier-college1.jpg",
          lat: -37.812269,
          lng: 145.031685
        }
      ]
    }, {
      name: "Western Australia",
      range: 2000000,
      lat: -27.6728168,
      lng: 121.6283098,
      schools: [
        {
          name: "Mazenod College",
          logo: "http://catholicschoolsguide.com.au/wp-content/uploads/xavier-college1.jpg",
          lat: -32.006682,
          lng: 116.038843
        }, {
          name: "Perth College",
          logo: "http://catholicschoolsguide.com.au/wp-content/uploads/xavier-college1.jpg",
          lat: -31.931425,
          lng: 115.875297
        }
      ]
    }
  ];
  pan_through_states(schools_in_states);
  return setTimeout(run_slide_show, 1000 * 30);
};

run_slide_show();
